### ISSUE TITLE
Remove the hard coded two-input structure for Sector

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/MPSGE.jl#13]
At least I think we should probably do that, but not entirely sure, actually.

**Comment by davidanthoff** [comment]
First step is to actually understand what equation MPSGE creates for a production function with more than two inputs :)

**Comment by davidanthoff** [comment]
Also done, I think?

**Comment by EliLazarus** [comment]
I believe so, yes. Thanks for closing.
