### ISSUE TITLE
Add option to output only explicit variables (solve and algebraic)

### ISSUE THREAD

**Issue by EliLazarus** [anthofflab/MPSGE.jl#136]
I guess add a method to both solve!() and algebraic_version() that does that instead.

**Comment by mitchphillipson** [comment]
I would expand this to be "Only generate explicit variable by default". Generating implicit variables greatly explodes the size of the model, for example the MPSGE.jl national model has ~5000 variables, the GAMS MPSGE has ~300. This is really going to have an impact in the state model which has ~30,000 variables in GAMS.

**Comment by EliLazarus** [comment]
With #145 , solve! now outputs only the explicit variables, including all nested variables given nested names.
I added a algebraic_version_main(model) function.
I will add a different issue to add clear functionality to output the implicit expression values. (which exist, but now the user won't ever see)
