### ISSUE TITLE
Speed: Convert Implicit Variables/Constraints to @expressions

### ISSUE THREAD

**Issue by EliLazarus** [anthofflab/MPSGE.jl#137]
We currently generate separate variables and constraint equations for the implicit Compensated Supply, Compensated Demand, and Final Demand. It's nice that they're all articulated and reported, but they are all passed to the Solver which assumedly makes it much slower.
The alternative would be to turn them into something like JuMP @expression s, and then include them in the variable constraints instead of the implicit variables. My understanding is that that should be equivalent in the construction of the constriants, while generating a fraction of the # variables and constraints.
Pluses: In theory much faster, assuming much fewer but long elaborate constraints are faster.
Minuses: We would lose the nice simple printing of the variable expressions if they have everything in them; we would no longer automatically output all the elements, which can be quite useful.
- Q: Is it possible to have the best of both? Assuming the speed improvement is real, can we set up a structure that 1) generates the variable equations without the full expressions, incorporating equivalent symbols for the expression instead, and 2) can we set up a show attribute to output all expressions with generated variable names parallel to what we have now.

**Comment by mitchphillipson** [comment]
I think this is the same as #136 . 

This is possible and it's going to require a bit of a rethink on how these equations are generated. This is the idea we discussed earlier, having a tree structure that recursively builds an expression matrix. I believe all the compensated demand/supply information is encapsulated here.

I'm going to discuss this with Tom on Wednesday and form a concrete plan.

**Comment by EliLazarus** [comment]
#145 merged
