### ISSUE TITLE
Fix printing once we are on JuMP 1.0

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/MPSGE.jl#58]
https://github.com/jump-dev/JuMP.jl/pull/2874

**Comment by odow** [comment]
While you're at it, JuMP v1.2 is going to introduce some breaking (internal) changes to the nonlinear API:
https://discourse.julialang.org/t/ann-upcoming-refactoring-of-jumps-nonlinear-api/83052/6

This should only affect things like this:
https://github.com/anthofflab/MPSGE.jl/blob/c20c396901c147a0c1cb6690ee9adc47e9e59045/src/algebraic_wrapper.jl#L96
where you reach into the undocumented internals.

Please ping me if you need a hand when updating.

x-ref: https://github.com/jump-dev/JuMP.jl/pull/2955
