### ISSUE TITLE
Figure out a way to set the numeraire good

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/MPSGE.jl#9]
Right now it is hard coded, we need to find some way to remove the hard coded aspect of it, and then also probably provide a way for users to specify which good they want as the numeraire good. Not clear to me right now how one specifies that in the GAMS version of MPSGE.

**Comment by davidanthoff** [comment]
This is no longer hard coded, but we still need to fix this.

**Comment by EliLazarus** [comment]
set_fixed!([Variable], [Boolean]):
for commodities, including for indexed commodities.
