### ISSUE TITLE
Indexed Taxes: syntax or functionality

### ISSUE THREAD

**Issue by EliLazarus** [anthofflab/MPSGE.jl#95]
We need to implement taxes for indexed productions/commodities.
(Or possibly I just need to understand the syntax required).

**Comment by davidanthoff** [comment]
I took a look, and I think it should already all just work? Both `Output` and `Input` is already for a specific commodity always, i.e. a specific element in an indexed commodity, so I think that means we actually don't need anything extra there? Maybe I'm missing something...

**Comment by EliLazarus** [comment]
Yes, I think you're right. And I tested sytax that ran on example 3 to double check.
